apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: fastapi-tut
  labels:
    app: fastapi
    group: tutorial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: formops:latest
        volumeMounts:
          - name: form-data-volume
            mountPath: /app/Data
        imagePullPolicy: Never  # Use local image, don't pull from registry
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          periodSeconds: 10
          initialDelaySeconds: 10
      volumes:
        - name: form-data-volume
          emptyDir: {}

